### ISSUE TITLE
add back pdf?

### ISSUE THREAD

**Issue by jlopp** [karask/bitcoin-textbook#1]
Hi, I was linking to https://github.com/karask/bitcoin-textbook/blob/master/bitcoin-textbook.pdf from my resources site and it looks like you're no longer building the pdf. Can you add back a recently compiled version?

**Comment by karask** [comment]
Hi, I am improving/extending the book nowadays and one of my old machines had *.pdf   in .gitignore  which caused this.

Thanks for letting me know. It is back now. 

This happened a few days ago. How come you found out so quickly.. do you have a script checking for the links?

**Comment by jlopp** [comment]
Thanks. Yes, I do indeed run broken link checker scripts across my whole site; with nearly 2,000 links to different resources it was insanity not to automate it!

**Comment by karask** [comment]
True :)

Btw, great resources list that I typically suggest to people than need to learn.
